package com.example.web_client;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.net.URI;

@SpringBootApplication
public class WebClientApplication {

	public static void main(String[] args) {

//		SpringApplication.run(WebClientApplication.class, args);

		MultiValueMap<String, String> bodyValues = new LinkedMultiValueMap<>();

		bodyValues.add("ctl00$ContentPlaceHolder1$ctl00$txtTaiKhoa", "DH52007012");
		bodyValues.add("ctl00$ContentPlaceHolder1$ctl00$ucDangNhap$txtMatKhau", "TGKneitov3110");
		bodyValues.add("__EVENTTARGET", "");
		bodyValues.add("__EVENTARGUMENT", "");

		bodyValues.add("__VIEWSTATE", "/wEPDwUKLTMxNjc3NTM3NQ9kFgJmD2QWBGYPZBYCAgEPFgIeB2NvbnRlbnRkZAIBD2QWCAIDD2" +
				"QWAmYPZBYCAgEPZBYMZg8PFgIeBFRleHQFDENow6BvIGLhuqFuIGRkAgEPDxYEHglGb3JlQ29sb3IJADP//x4EXyFTQgIEZG" +
				"QCAg8PFgQfAgkAM///HwMCBGRkAgMPDxYGHwEFGFRoYXkgxJHhu5VpIG3huq10IGto4bqpdR8CCQAz//8fAwIEZGQCBA8PFg" +
				"QfAgkAM///HwMCBGRkAgUPDxYGHwEFDcSQxINuZyBOaOG6rXAfAgkAM///HwMCBGRkAgUPZBbCAQIBDw8WBB4IQ3NzQ2xhc3" +
				"MFCG91dC1tZW51HwMCAmQWAmYPDxYCHwEFC1RSQU5HIENI4bumZGQCAw8PFgQfBAUIb3V0LW1lbnUfAwICZBYCAgEPDxYCH" +
				"wEFF0RBTkggTeG7pEMgQ0jhu6hDIE7Egk5HZGQCBQ8PFgQfBAUIb3V0LW1lbnUfAwICZBYCAgEPDxYCHwEFG0RNIENI4b" +
				"uoQyBOxIJORyDEkMOBTkggR0nDgWRkAgcPDxYEHwQFCG91dC1tZW51HwMCAmRkAgkPDxYGHwQFCG91dC1tZW51HwMCAh" +
				"4HVmlzaWJsZWhkFgICAQ8PFgIfAQUVxJDEgk5HIEvDnSBNw5ROIEjhu4xDZGQCCw8PFgQfBAUIb3V0LW1lbnUfAwICZGQCDQ8" +
				"PFgYfBAUIb3V0LW1lbnUfAwICHwVoZBYCAgEPDxYCHwEFB1hFTSBUS0JkZAIPDw8WBB8EBQhvdXQtbWVudR8DAgJkZAIRDw8WBh8" +
				"EBQhvdXQtbWVudR8DAgIfBWhkFgJmDw8WAh8BBQ5YRU0gTOG7ikNIIFRISWRkAhMPDxYGHwQFCG91dC1tZW51HwMCAh8FaGQWA" +
				"gIBDw8WAh8BBRRYRU0gTOG7ikNIIFRISSBM4bqgSWRkAhUPDxYGHwQFCG91dC1tZW51HwMCAh8FaGQWAgIBDw8WAh8BBRFYRU0gT" +
				"OG7ikNIIFRISSBHS2RkAhcPDxYGHwQFCG91dC1tZW51HwMCAh8FaGRkAhkPDxYEHwQFCG91dC1tZW51HwMCAmRkAhsPDxYGHwQFC" +
				"G91dC1tZW51HwMCAh8FaGQWAgIBDw8WAh8BBQ5YRU0gSOG7jEMgUEjDjWRkAh0PDxYEHwQFCG91dC1tZW51HwMCAmRkAh8PDxYG" +
				"HwQFCG91dC1tZW51HwMCAh8FaGQWAgIBDw8WAh8BBQtYRU0gxJBJ4buCTWRkAiEPDxYGHwQFCG91dC1tZW51HwMCAh8FaGRkAiM" +
				"PDxYEHwQFCG91dC1tZW51HwMCAmRkAiUPDxYEHwQFCG91dC1tZW51HwMCAmRkAicPDxYEHwQFCG91dC1tZW51HwMCAmRkAikPDx" +
				"YEHwQFCG91dC1tZW51HwMCAmRkAisPDxYEHwQFCG91dC1tZW51HwMCAmQWAgIBDw8WAh8BBQlYRU0gQ1TEkFRkZAItDw8WBB8E" +
				"BQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQULWEVNIE3DlE4gVFFkZAIvDw8WBB8EBQhvdXQtbWVudR8DAgJkZAIxDw8WBB8EBQhv" +
				"dXQtbWVudR8DAgJkZAIzDw8WBh8EBQhvdXQtbWVudR8DAgIfBWhkFgICAQ8PFgIfAQUSU+G7rEEgVFQgQ8OBIE5Iw4JOZGQCNQ8PFgY" +
				"fBAUIb3V0LW1lbnUfAwICHwVnZBYCAgEPDxYCHwEFDkfDk1Agw50gS0nhur5OZGQCNw8PFgYfBAUIb3V0LW1lbnUfAwICHwVoZBYC" +
				"Zg8PFgIfAQUQU+G7rEEgTMOdIEzhu4pDSGRkAjkPDxYEHwQFCG91dC1tZW51HwMCAmQWAgIBDw8WAh8BBQ9RTFNWIGzhu5twIENWS" +
				"FRkZAI7Dw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUiS+G6vlQgUVXhuqIgU0lOSCBWScOKTiDEkMOBTkggR0nDgWRkAj" +
				"0PDxYEHwQFCG91dC1tZW51HwMCAmRkAj8PDxYEHwQFCG91dC1tZW51HwMCAmQWAgIBD2QWAmYPDxYCHwEFGcSQw4FOSCBHScOBIEdJ" +
				"4bqiTkcgROG6oFlkZAJBDw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUUxJDEgk5HIEvDnSBUSEkgTOG6oElkZAJDDw8WB" +
				"B8EBQhvdXQtbWVudR8DAgJkZAJFDw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUSxJBLIENIVVnDik4gTkfDgE5IZGQCRw" +
				"8PFgQfBAUIb3V0LW1lbnUfAwICZGQCSQ8PFgQfBAUIb3V0LW1lbnUfAwICZBYCAgEPDxYCHwEFFktRIFjDiVQgVOG7kFQgTkdISeG7" +
				"hlBkZAJLDw8WBB8EBQhvdXQtbWVudR8DAgJkZAJNDw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUaQ8OCVSBI4buOSSBU" +
				"SMav4bucTkcgR+G6tlBkZAJPDw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUTxJBLIEtIw5NBIExV4bqsTiBUTmRkAlEPD" +
				"xYEHwQFCG91dC1tZW51HwMCAmQWAgIBDw8WAh8BBQ5OSOG6rFAgxJBJ4buCTWRkAlMPDxYEHwQFCG91dC1tZW51HwMCAmRkAlU" +
				"PDxYEHwQFCG91dC1tZW51HwMCAmRkAlcPDxYEHwQFCG91dC1tZW51HwMCAmRkAlkPDxYEHwQFCG91dC1tZW51HwMCAmQWAgIBDw" +
				"8WAh8BBR5YRU0gxJBJ4buCTSBNw5ROIEdJ4bqiTkcgROG6oFlkZAJbDw8WBB8EBQhvdXQtbWVudR8DAgJkZAJdDw8WBB8EBQhvdXQ" +
				"tbWVudR8DAgJkZAJfDw8WBB8EBQhvdXQtbWVudR8DAgJkZAJhDw8WBB8EBQhvdXQtbWVudR8DAgJkZAJjDw8WBB8EBQhvdXQ" +
				"tbWVudR8DAgJkZAJlDw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUmVEjhu5BORyBLw4ogR0nhuqJORyBWScOKTiBEVVnh" +
				"u4ZUIEtRREtkZAJnDw8WBB8EBQhvdXQtbWVudR8DAgJkZAJpDw8WBB8EBQhvdXQtbWVudR8DAgJkZAJrDw8WBB8EBQhvdXQtbWVudR" +
				"8DAgJkZAJtDw8WBh8EBQhvdXQtbWVudR8DAgIfBWdkZAJvDw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUUSMav4buaTkc" +
				"gROG6qk4gxJBLTUhkZAJxDw8WBB8EBQhvdXQtbWVudR8DAgJkZAJzDw8WBB8EBQhvdXQtbWVudR8DAgJkZAJ1Dw8WBB8EBQhvdXQtb" +
				"WVudR8DAgJkZAJ3Dw8WBB8EBQhvdXQtbWVudR8DAgJkZAJ5Dw8WBB8EBQhvdXQtbWVudR8DAgJkZAJ7Dw8WBB8EBQhvdXQtbWVudR" +
				"8DAgJkZAJ9Dw8WBB8EBQhvdXQtbWVudR8DAgJkZAJ/Dw8WBB8EBQhvdXQtbWVudR8DAgJkZAKBAQ8PFgQfBAUIb3V0LW1lbnUfAwIC" +
				"ZGQCgwEPDxYEHwQFCG91dC1tZW51HwMCAmRkAoUBDw8WBB8EBQhvdXQtbWVudR8DAgJkZAKHAQ8PFgQfBAUIb3V0LW1lbnUfAwICZG" +
				"QCiQEPDxYEHwQFCG91dC1tZW51HwMCAmRkAosBDw8WBB8EBQhvdXQtbWVudR8DAgJkZAKNAQ8PFgQfBAUIb3V0LW1lbnUfAwICZBY" +
				"CAgEPDxYCHwEFF0jDk0EgxJDGoE4gxJBJ4buGTiBU4busZGQCjwEPDxYEHwQFCG91dC1tZW51HwMCAmQWAgIBDw8WAh8BBRZOR0jh" +
				"u4ggROG6oFkgROG6oFkgQsOZZGQCkQEPDxYEHwQFCG91dC1tZW51HwMCAmQWAgIBDw8WAh8BBRfEkMSCTkcgS8OdIE5HSOG7iCBQSM" +
				"OJUGRkApMBDw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUSxJDEgk5HIEvDnSBDT0kgVEhJZGQClQEPDxYEHwQFCG91dC1" +
				"tZW51HwMCAmQWAgIBDw8WAh8BBRJYRU0gTOG7ikNIIENPSSBUSElkZAKXAQ8PFgQfBAUIb3V0LW1lbnUfAwICZBYCAgEPDxYCHwEF" +
				"G0tRIE5HSEnDik4gQ+G7qFUgS0hPQSBI4buMQ2RkApkBDw8WBB8EBQhvdXQtbWVudR8DAgJkZAKbAQ8PFgQfBAUIb3V0LW1lbnUfA" +
				"wICZBYCAgEPZBYCZg8PFgIfAQUkxJDEgk5HIEvDnSBYSU4gR0nhuqRZIENI4buoTkcgTkjhuqxOZGQCnQEPDxYEHwQFCG91dC1tZ" +
				"W51HwMCAmRkAp8BDw8WBB8EBQhvdXQtbWVudR8DAgJkZAKhAQ8PFgQfBAUIb3V0LW1lbnUfAwICZBYCAgEPDxYCHwEFFUPhuqhNI" +
				"E5BTkcgU0lOSCBWScOKTmRkAqMBDw8WBB8EBQhvdXQtbWVudR8DAgJkZAKlAQ8PFgQfBAUIb3V0LW1lbnUfAwICZGQCpwEPDxYEHwQ" +
				"FCG91dC1tZW51HwMCAmRkAqkBDw8WBB8EBQhvdXQtbWVudR8DAgJkFgICAQ8PFgIfAQUkQsOBTyBCSeG7glUgUEjhu6RDIFbhu6QgT" +
				"MODTkggxJDhuqBPZGQCqwEPDxYEHwQFCG91dC1tZW51HwMCAmRkAq0BDw8WBB8EBQhvdXQtbWVudR8DAgJkZAKvAQ8PFgQfBAUIb3V0" +
				"LW1lbnUfAwICZGQCsQEPDxYEHwQFCG91dC1tZW51HwMCAmRkArMBDw8WBB8EBQhvdXQtbWVudR8DAgJkZAK1AQ8PFgQfBAUIb3V0LW" +
				"1lbnUfAwICZGQCtwEPDxYEHwQFCG91dC1tZW51HwMCAmRkArkBDw8WBB8EBQhvdXQtbWVudR8DAgJkZAK7AQ8PFgQfBAUIb3V0LW1l" +
				"bnUfAwICZGQCvQEPDxYEHwQFCG91dC1tZW51HwMCAmRkAr8BDw8WBB8EBQhvdXQtbWVudR8DAgJkZALBAQ8PFgQfBAUIb3V0LW1lb" +
				"nUfAwICZGQCBw9kFgICAQ9kFgJmD2QWAgIDD2QWEAIBDw8WAh8BBRNRdcOqbiBt4bqtdCBraOG6qXUhZGQCAw8PFgIfAQUSVMOqbiD" +
				"EkMSDbmcgTmjhuq1wZGQCBQ8PZBYCHgpvbmtleXByZXNzBUBidXR0b25fY2xpY2sodGhpcywnY3RsMDBfQ29udGVudFBsYWNlSG9sZGV" +
				"yMV9jdGwwMF9idG5EYW5nTmhhcCcpZAIHDw8WAh8BBQxN4bqtdCBLaOG6qXVkZAIJDw9kFgIfBgVAYnV0dG9uX2NsaWNrKHRoaXMs" +
				"J2N0bDAwX0NvbnRlbnRQbGFjZUhvbGRlcjFfY3RsMDBfYnRuRGFuZ05oYXAnKWQCCw8PFgIfAQUNxJDEg25nIE5o4bqtcGRkAg0" +
				"PDxYCHwVoZGQCDw8PFgIfBWhkZAIJD2QWCAIBDw8WAh8BBWNDb3B5cmlnaHQgwqkyMDA5IFRyxrDhu51uZyDEkOG6oWkgSOG7jWM" +
				"gQ8O0bmcgTmdo4buHIFPDoGkgR8Oybi4gUXXhuqNuIGzDvSBi4bufaSBQaMOybmcgxJDDoG8gVOG6oW9kZAIDDw8WAh8BBQtUcmF" +
				"uZyBDaOG7p2RkAgUPDxYCHwEFLVRoaeG6v3Qga+G6vyBi4bufaSBjdHkgUGjhuqduIG3hu4FtIEFuaCBRdcOibmRkAgcPDxYCHw" +
				"EFDMSQ4bqndSBUcmFuZ2RkZA==");

		String url = "http://daotao1.stu.edu.vn/";

		WebClient client = WebClient.create(url);

		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);

		// Gửi yêu cầu POST
		Mono<String> responseMono = client.post()
				.uri("default.aspx?page=dangnhap")
				.body(BodyInserters.fromFormData(bodyValues))
				.headers(httpHeaders -> httpHeaders.addAll(headers))
				.retrieve()
				.bodyToMono(String.class);

		responseMono.subscribe(
				response -> System.out.println("Login response: " + response),
				error -> System.err.println("Login failed: " + error.getMessage())
		);

		System.out.printf(responseMono.block());

	}

}
